version: '3'

tasks:
  build:
    cmds:
      - task fmt
      - go build -C ./src/ -v -o ../bin/Server
  fmt:
    cmds:
      - go fmt -C ./src/
  run:
    cmds:
      - task fmt
      - task build
      - ./bin/Server

